### ISSUE TITLE
Project 3 - Review my app (My Simple Tweets) to [Android Bootcamp February 2016]

### ISSUE THREAD

**Issue by cbaja** [cbaja/MySimpleTweets#1]
My app is complete, please review.**/cc @codepathreview @codepath**

Carly BAJA

**Comment by codepathreview** [comment]
Nice work. A few notes after checking out the code:
- Good layout, proper view naming, usage of sp/dp, margin and relative placement rules
- Good use of string resources for text values
- Glad you thought about error handling for invalid or empty input cases
- Consider adding [progress bars](http://guides.codepath.com/android/Handling-ProgressBars#progress-within-actionbar) to your app whenever a network request goes out
- Consider including a check to see if internet is available to detect any network failures. Show an approrpiate message in case of failure.
- Good to see you were able to format the timestamp cleanly
- Nice to see you used the SwipeRefreshLayout for easy timeline refreshes
- Good to see you added the tweet to the home timeline after you posted new on compose
- Nice touch with the character count being displayed while the user composes a tweet
- Good to see you added ActiveAndroid annotations to the models

Here's a detailed [Project 3 Feedback Guide here](http://courses.codepath.com/snippets/intro_to_android/project_3_feedback) which covers the most common issues with this submitted project. Read through the feedback guide point-by-point to determine how you could improve your submission. 

Let us know if you have any other thoughts or questions about this assignment. Hopefully by now you feel pretty comfortable with all the major pieces to basic Android apps (Views, Controllers, ActionBar, Navigation, Models, Authentication, API Communication, Persistence, et al) and see how they all fit together. We are close now to a turning point in the course where you should be hitting a "critical mass" towards your knowledge of Android.
